name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  django:
    runs-on: ubuntu-latest
    environment: virnect
    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DJANGO_DEBUG: true
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - name: Set Up Python 3.10.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.10
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      - name: Set Up Database
        run: |
          python manage.py makemigrations
          python manage.py migrate
      - name: Check CodeStyle
        run: |
          flake8
      - name: Run Tests
        run: |
          python manage.py test
  react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js 19
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: Install Dependencies
        run: |
          npm install -C core/web
      - name: Check CodeStyle
        run: |
          ./core/web/node_modules/.bin/eslint ./core/web/**/*.jsx
      - name: Generate Build
        run: |
          npm run build -C core/web
